# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aladin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('forecast_time', models.DateTimeField(db_index=True)),
                ('timedelta', models.IntegerField()),
                ('picdata', models.TextField()),
                ('processed', models.FileField(blank=True, null=True, upload_to=b'processed/aladin')),
            ],
            options={
                'ordering': ('-forecast_time', '-timedelta'),
            },
        ),
        migrations.CreateModel(
            name='RadarPadavin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(db_index=True, unique=True)),
                ('picdata', models.TextField()),
                ('format_id', models.IntegerField(null=True)),
                ('processed', models.FileField(blank=True, null=True, upload_to=b'processed/radar')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Toca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(db_index=True, unique=True)),
                ('picdata', models.TextField()),
                ('processed', models.FileField(upload_to=b'processed/toca')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='aladin',
            unique_together=set([('forecast_time', 'timedelta')]),
        ),
    ]
