# Generated by Django 4.1.5 on 2023-01-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aladin',
            name='processed',
            field=models.FileField(blank=True, null=True, upload_to='processed/aladin'),
        ),
        migrations.AlterField(
            model_name='radarpadavin',
            name='processed',
            field=models.FileField(blank=True, null=True, upload_to='processed/radar'),
        ),
        migrations.AlterField(
            model_name='toca',
            name='processed',
            field=models.FileField(upload_to='processed/toca'),
        ),
    ]
